force-app/main/default/objects/Locations__c/Locations__c.object-meta.xml
<CustomObject>
    <label>Locations</label>
    <nameField>
        <label>Locations Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Locations__c/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <label>Area</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Area</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/MonthlyPayment__c/MonthlyPayment__c.object-meta.xml
<CustomObject>
    <label>Monthly Payment</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Monthly Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Monthly Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MonthlyPayment__c/fields/Desk_Capacity__c.field-meta.xml
<CustomField>
    <fullName>Desk_Capacity__c</fullName>
    <formula>IF( ISBLANK( OrderItem__c ),OpportunityLineItem__r.Desk_Count__c,  OrderItem__r.Number_of_desks__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Desk Capacity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MonthlyPayment__c/fields/FinalPrice__c.field-meta.xml
<CustomField>
    <fullName>FinalPrice__c</fullName>
    <formula>Price__c * (1 + Discount__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Claculated Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/MonthlyPayment__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Location of the Office</description>
    <label>Location</label>
    <referenceTo>Locations__c</referenceTo>
    <relationshipLabel>Monthly Payments</relationshipLabel>
    <relationshipName>MonthlyPayments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MonthlyPayment__c/fields/Room__c.field-meta.xml
<CustomField>
    <fullName>Room__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Monthly Payments</relationshipLabel>
    <relationshipName>Monthly_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MonthlyPayment__c/fields/Segmentation__c.field-meta.xml
<CustomField>
    <fullName>Segmentation__c</fullName>
    <formula>IF(
    AND(NOT(ISPICKVAL(Contract__r.Origin__c, &apos;Renewal&apos;)) ,MonthIndex__c = 1, NOT(ISBLANK(OrderItem__c))),
    &apos;New business&apos;,
    IF(
        AND(
            MonthIndex__c &gt; 1,
            Access_Type__c = &apos;Monthly&apos;,
            ISNULL(OrderItem__r.Contract__r.Contract_Termination_Date__c),
            NOT(ISBLANK(OrderItem__c))
        ),
        &apos;Monthly/recurring revenue&apos;,
        IF(
            AND(
                ISBLANK(OrderItem__c),
                ISPICKVAL(OpportunityLineItem__r.Opportunity.Type, &apos;New Business&apos;),   NOT(ISPICKVAL(OpportunityLineItem__r.Opportunity.StageName ,&apos;Closed Won&apos;)), NOT(ISPICKVAL(OpportunityLineItem__r.Opportunity.StageName ,&apos;Closed Lost&apos;)),
                MonthIndex__c &gt; 0,
                MonthIndex__c &lt; 4
            ),
            &apos;Potential new business&apos;,
            IF(
                AND(
                    NOT(ISNULL(OrderItem__r.Contract__r.Contract_Termination_Date__c)),
                    NOT(ISBLANK(OrderItem__c))
                ),
                &apos;Confirmed exit dates&apos;,
                IF(
                    AND(
                        MonthIndex__c &gt; 1,
                        Access_Type__c = &apos;Periodic&apos;,
                        NOT(Contract__r.Auto_Renewal__c), Contract__r.StartDate &gt;=TODAY(),
                        NOT(ISBLANK(OrderItem__c))
                    ),
                    &apos;Periodic without renewal&apos;,
                    IF(
                        AND(
                             MonthIndex__c &gt; 1,
                             Access_Type__c = &apos;Periodic&apos;,
                             Contract__r.Auto_Renewal__c,
                             NOT(ISBLANK(OrderItem__c)),  ISNULL(Contract__r.Contract_Termination_Date__c) ,  Start_date__c &lt;  Contract__r.Auto_Renewal_Cancellation_Deadline__c 
                            ), &apos;Periodic with potential renewal&apos;,IF(AND(   ISPICKVAL(Contract__r.Origin__c, &apos;Renewal&apos;)  ),&apos;Potential renewal&apos;,&apos;None&apos;)
                       )
                )
            )
        )
    )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Segmentation</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MonthlyPayment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF(
    OR(
        NOT(ISPICKVAL(OrderItem__r.Contract__r.Status, &quot;Activated&quot;)) &amp;&amp; 
        NOT(ISPICKVAL(OrderItem__r.Contract__r.Status, &quot;Pending&quot;)),
        
        AND(
            NOT(ISBLANK(OrderItem__r.Contract__r.Contract_Termination_Date__c)),
            OrderItem__r.Contract__r.Contract_Termination_Date__c &lt; TODAY()
        ),
        
        AND(
            NOT(ISBLANK(OrderItem__r.Contract__r.EndDate)),
            OrderItem__r.Contract__r.EndDate &lt; End_date__c
        ),
        
        AND(
            NOT(ISBLANK(OrderItem__r.Contract__r.StartDate)),
            OrderItem__r.Contract__r.StartDate &gt; Start_date__c
        ),
        
        NOT(ISPICKVAL(OrderItem__r.Approval_Status__c, &quot;Activated&quot;)),
        
        AND(
            OR(
                ISPICKVAL(OrderItem__r.Change_Action_Type__c, &quot;Removed&quot;),
                ISPICKVAL(OrderItem__r.Change_Action_Type__c, &quot;Changed&quot;)
            ),
            NOT(ISBLANK(OrderItem__r.Change_Action_Effective_End_Date__c)),
            OrderItem__r.Change_Action_Effective_End_Date__c &lt; End_date__c
        ),
        
        OR(
            Start_date__c &lt; DATEVALUE(OrderItem__r.Start_Date_Time__c),
            End_date__c &gt; DATEVALUE(OrderItem__r.End_Date_Time__c)
        )
    ),
    &quot;Deactivated&quot;,
    &quot;Active&quot;
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Locations__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Locations__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Sub_Type__c</fullName>
    <label>Sub-Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hot Desk</fullName>
            </value>
            <value>
                <fullName>Open Space</fullName>
            </value>
            <value>
                <fullName>Office</fullName>
            </value>
            <value>
                <fullName>Suite</fullName>
            </value>
            <value>
                <fullName>Rent</fullName>
            </value>
            <value>
                <fullName>Daily HD</fullName>
            </value>
            <value>
                <fullName>Daily Office</fullName>
            </value>
            <value>
                <fullName>Meeting Rooms</fullName>
            </value>
            <value>
                <fullName>Event Space-Balcony, roof, Lounge</fullName>
            </value>
            <value>
                <fullName>Mini Cinema</fullName>
            </value>
            <value>
                <fullName>Classroom</fullName>
            </value>
            <value>
                <fullName>Parking spot</fullName>
            </value>
            <value>
                <fullName>Capsules</fullName>
            </value>
            <value>
                <fullName>Food / Refreshements</fullName>
            </value>
            <value>
                <fullName>IP/VLAN</fullName>
            </value>
            <value>
                <fullName>Credits(Meeting rooms windows)</fullName>
            </value>
            <value>
                <fullName>Print Units</fullName>
            </value>
            <value>
                <fullName>Storage Space</fullName>
            </value>
            <value>
                <fullName>Set Up Fee</fullName>
            </value>
            <value>
                <fullName>Restoration Fee</fullName>
            </value>
            <value>
                <fullName>Arnona</fullName>
            </value>
            <value>
                <fullName>Cleaning</fullName>
            </value>
            <value>
                <fullName>Electricity</fullName>
            </value>
            <value>
                <fullName>Management Fee</fullName>
            </value>
            <value>
                <fullName>Other- (all other fee)</fullName>
            </value>
            <value>
                <fullName>Podcast Room</fullName>
            </value>
            <value>
                <fullName>Maintenance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard Products</fullName>
            </value>
            <value>
                <fullName>On demand Products</fullName>
            </value>
            <value>
                <fullName>Extra for all products</fullName>
            </value>
            <value>
                <fullName>Extra for meter Products</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Area.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Tel Aviv - Modiin</fullName>
    </customValue>
    <customValue>
        <fullName>Ra&apos;anana</fullName>
    </customValue>
    <customValue>
        <fullName>Petah Tikva - Ramat Gan - Bnei Brak</fullName>
    </customValue>
    <customValue>
        <fullName>Tel Aviv</fullName>
    </customValue>
    <customValue>
        <fullName>Modiin</fullName>
    </customValue>
    <customValue>
        <fullName>Petah Tikva</fullName>
    </customValue>
    <customValue>
        <fullName>Bne Brak</fullName>
    </customValue>
    <customValue>
        <fullName>Ramat Gan</fullName>
    </customValue>
    <customValue>
        <fullName>Rishon LeZion</fullName>
    </customValue>
    <customValue>
        <fullName>Glilot Allied City</fullName>
    </customValue>
    <masterLabel>Area</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ForecastController.cls
/**
 * @description       : The ForecastController class retrieves and aggregates monthly payment data (MonthlyPayment__c) for opportunities, organizing it by location, product type, and date.
 *                       It provides methods for querying and wrapping data into a structured format (WrapData) for easier frontend display.
 * @author            : LAURIE CS
 * @group             :
 * @last modified on  : 2024-11-10
**/
public with sharing class ForecastController {


    @AuraEnabled(cacheable=true)
    public static List<WrapData> fetchPaymentsOfOpportunity() {
        List<WrapData> dataList = new List<WrapData>();

        String query = 'SELECT Id, Location__c, Location__r.Name, Location__r.Area__c, Segmentation__c, Opportunity__c, ' +
               'Start_date__c, Desk_Capacity__c, FinalPrice__c, Opportunity__r.Type, ' +
               'Room__r.Sub_Type__c, Room__r.Family, Room__r.Type__c ' +
               'FROM MonthlyPayment__c ' +
               'WHERE Start_date__c != null ';

        if(!Test.isRunningTest()){
            query += 'AND Status__c = \'Active\'';
        }

        // Query data including Segmentation__c and other relevant fields
        List<MonthlyPayment__c> payments = Database.query(query);

        // Map to group and aggregate data
        Map<String, AggregateWrapper> aggregatedData = new Map<String, AggregateWrapper>();

        for (MonthlyPayment__c payment : payments) {
            Integer month = payment.Start_date__c.month();
            Integer year = payment.Start_date__c.year();
            String key = payment.Segmentation__c + '-' + month + '-' + year;

            if (!aggregatedData.containsKey(key)) {
                aggregatedData.put(key, new AggregateWrapper(payment.Location__r.Name, payment.Segmentation__c,
                                                              month, year, payment.Location__r.Area__c,
                                                              payment.Opportunity__c, payment.Opportunity__r.Type,
                                                              payment.Room__r.Sub_Type__c, payment.Room__r.Family,
                                                              payment.Room__r.Type__c));
            }

            AggregateWrapper wrapper = aggregatedData.get(key);
            wrapper.deskNumber += payment.Desk_Capacity__c != null ? Integer.valueOf(payment.Desk_Capacity__c) : 0;
            wrapper.totalFinalPrice += payment.FinalPrice__c != null ? payment.FinalPrice__c : 0;
        }

        // Convert aggregated data into WrapData instances
        for (AggregateWrapper wrapper : aggregatedData.values()) {
            dataList.add(new WrapData(wrapper.locationName, wrapper.segmentation, wrapper.month, wrapper.year,
                                      wrapper.deskNumber, wrapper.totalFinalPrice, wrapper.type, wrapper.area,
                                      wrapper.productFamily, wrapper.productType, wrapper.productSubType,
                                      wrapper.opportunity));
        }

        return dataList;
    }

    // Helper class to aggregate data
    private class AggregateWrapper {
        public String locationName;
        public String segmentation;
        public Integer month;
        public Integer year;
        public Integer deskNumber = 0;
        public Decimal totalFinalPrice = 0;
        public String type;
        public String area;
        public String productFamily;
        public String productType;
        public String productSubType;
        public String opportunity;

        public AggregateWrapper(String locationName, String segmentation, Integer month, Integer year, String area,
                                String opportunity, String type, String productSubType, String productFamily,
                                String productType) {
            this.locationName = locationName;
            this.segmentation = segmentation;
            this.month = month;
            this.year = year;
            this.area = area;
            this.opportunity = opportunity;
            this.type = type;
            this.productFamily = productFamily;
            this.productType = productType;
            this.productSubType = productSubType;
        }
    }



     /**
     * @description : Queries the `MonthlyPayment__c` records based on a dynamic filter clause.
     * @param whereClause : A string representing additional WHERE conditions for the SOQL query.
     * @return : List of `MonthlyPayment__c` records that match the query conditions.
     **/
    @AuraEnabled(cacheable=true)
    public static List<MonthlyPayment__c> queryMonthlyPayments(String whereClause) {
        String query = 'SELECT Id, Name, Start_date__c, End_date__c, Desk_Capacity__c, Opportunity__r.Type, Contract__r.Type__c, Products_Name__c, Location__r.Name , FinalPrice__c, Contract__r.End_Date__c, Segmentation__c  FROM MonthlyPayment__c  ';

        if(whereClause != ''){
            query += ' WHERE ' + whereClause ;
            if(!Test.isRunningTest()){
                query += 'AND Status__c = \'Active\'';
            }

        }
        List<MonthlyPayment__c> pay = Database.query(query);
        return pay;
    }



    /**
     * @description : Inner class `WrapData` that represents aggregated payment data, encapsulating details about location, segmentation, date, product information, and payment totals.
     **/
    public class WrapData {
        @AuraEnabled
        public String locationName { get; set; }
        @AuraEnabled
        public String segmentation { get; set; }
        @AuraEnabled
        public Integer month { get; set; }
        @AuraEnabled
        public Integer year { get; set; }
        @AuraEnabled
        public Integer deskNumber { get; set; }
        @AuraEnabled
        public Decimal totalFinalPrice { get; set; }
        @AuraEnabled
        public String type { get; set; }
        @AuraEnabled
        public String area { get; set; }
        @AuraEnabled
        public String productFamily { get; set; }
        @AuraEnabled
        public String productType { get; set; }
        @AuraEnabled
        public String productSubType { get; set; }
        @AuraEnabled
        public String opportunity { get; set; }


        public WrapData(String locationName, String segmentation,  Integer month, Integer year, Integer DeskNumber, Decimal totalFinalPrice, String type, String area, string productFamily, string productType, string productSubType, string opportunity) {
            this.locationName = locationName;
            this.segmentation = segmentation;
            this.month = month;
            this.year = year;
            this.deskNumber = deskNumber;
            this.totalFinalPrice = totalFinalPrice;
            this.type = type;
            this.area = area;
            this.productFamily = productFamily;
            this.productType = productType;
            this.productSubType = productSubType;
            this.opportunity = opportunity;
        }
    }
}