force-app/main/default/objects/Locations__c/Locations__c.object-meta.xml
<CustomObject>
    <label>Locations</label>
    <nameField>
        <label>Locations Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Locations__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Locations__c/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <label>Area</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Area</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Locations__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Tel Aviv</fullName>
            </value>
            <value>
                <fullName>Bnei Brak</fullName>
            </value>
            <value>
                <fullName>Ra&apos;anana</fullName>
            </value>
            <value>
                <fullName>Modiin</fullName>
            </value>
            <value>
                <fullName>Ramat Gan</fullName>
            </value>
            <value>
                <fullName>Petah Tikva</fullName>
            </value>
            <value>
                <fullName>Rishon LeZion</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Locations__c/fields/Site_Name__c.field-meta.xml
<CustomField>
    <fullName>Site_Name__c</fullName>
    <label>Site Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Locations__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Locations__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard Products</fullName>
            </value>
            <value>
                <fullName>On demand Products</fullName>
            </value>
            <value>
                <fullName>Extra for all products</fullName>
            </value>
            <value>
                <fullName>Extra for meter Products</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Area.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Tel Aviv - Modiin</fullName>
    </customValue>
    <customValue>
        <fullName>Ra&apos;anana</fullName>
    </customValue>
    <customValue>
        <fullName>Petah Tikva - Ramat Gan - Bnei Brak</fullName>
    </customValue>
    <customValue>
        <fullName>Tel Aviv</fullName>
    </customValue>
    <customValue>
        <fullName>Modiin</fullName>
    </customValue>
    <customValue>
        <fullName>Petah Tikva</fullName>
    </customValue>
    <customValue>
        <fullName>Bne Brak</fullName>
    </customValue>
    <customValue>
        <fullName>Ramat Gan</fullName>
    </customValue>
    <customValue>
        <fullName>Rishon LeZion</fullName>
    </customValue>
    <customValue>
        <fullName>Glilot Allied City</fullName>
    </customValue>
    <masterLabel>Area</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AddOppProductController_Test.cls
@isTest
public with sharing class AddOppProductController_Test {

    @testSetup
    static void setup() {
        Locations__c loc = new Locations__c(
            Name = 'BSR City',
            City__c = 'Petah Tikva',
            Site_Name__c = 'BSR City',
            Address__c = 'בניין Y - השחם 3 פינת תוצרת הארץ 1, פתח תקווה',
            Area__c = 'Petah Tikva - Ramat Gan - Bnei Brak'
        );
        insert loc;

        Account acc = new Account(Name = 'Test Account');
        insert acc;

        Id pricebookId = Test.getStandardPricebookId();

        Product2 prod = new Product2(Name = 'SLA: Bronze', Location__c = loc.Id, Type__c = 'Standard Products', IsActive = true);
        insert prod;

        PricebookEntry standardPBE = new PricebookEntry(
            Pricebook2Id = pricebookId,
            Product2Id = prod.Id,
            UnitPrice = 1000,
            IsActive = true
        );
        insert standardPBE;

        Opportunity opp1 = new Opportunity(
            Name = 'Test On demand Opportunity',
            CloseDate = Date.today().addMonths(1),
            StageName = 'New',
            Location__c = loc.Id,
            Pricebook2Id = pricebookId,
            RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('On demand Opportunity').getRecordTypeId()
        );

        Opportunity opp2 = new Opportunity(
            Name = 'Test Standard Opportunity',
            CloseDate = Date.today().addMonths(1),
            StageName = 'New',
            Location__c = loc.Id,
            Pricebook2Id = pricebookId,
            RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Standard Opportunity').getRecordTypeId()
        );

        insert new List<Opportunity> {opp1, opp2};
        
    }

    @isTest
    static void getProductsByOppLocationOnDemand_test() {
        Id recTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('On demand Opportunity').getRecordTypeId();

        Opportunity opp = [SELECT Id, Name FROM Opportunity WHERE RecordTypeId=:recTypeId LIMIT 1];
        Id oppId = opp.Id;
        List<AddOppProductController.ProductData> products = AddOppProductController.getProductsByOppLocation(oppId);
    }

    @isTest
    static void getProductsByOppLocationstandard_test() {
        Id recTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Standard Opportunity').getRecordTypeId();

        Opportunity opp = [SELECT Id, Name FROM Opportunity WHERE RecordTypeId=:recTypeId LIMIT 1];
        Id oppId = opp.Id;
        List<AddOppProductController.ProductData> products = AddOppProductController.getProductsByOppLocation(oppId);
    }

    @isTest
    static void addProductsToOpp_test() {
        Opportunity opp = [SELECT Id, Name FROM Opportunity LIMIT 1];
        Id oppId = opp.Id;

        List<String> productEntryIds = new List<String>();

        AddOppProductController.addProductsToOpp(productEntryIds, oppId);
    }

}