force-app/main/default/objects/Contract/fields/Contract_Termination_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_Termination_Date__c</fullName>
    <inlineHelpText>Manual termination</inlineHelpText>
    <label>Contract Termination Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contract/fields/End_date__c.field-meta.xml
<CustomField>
    <fullName>End_date__c</fullName>
    <label>End date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Location</label>
    <referenceTo>Locations__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MonthlyPayment__c/MonthlyPayment__c.object-meta.xml
<CustomObject>
    <label>Monthly Payment</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Monthly Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Monthly Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MonthlyPayment__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Location of the Office</description>
    <label>Location</label>
    <referenceTo>Locations__c</referenceTo>
    <relationshipLabel>Monthly Payments</relationshipLabel>
    <relationshipName>MonthlyPayments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MonthlyPayment__c/fields/Room__c.field-meta.xml
<CustomField>
    <fullName>Room__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Monthly Payments</relationshipLabel>
    <relationshipName>Monthly_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Location</label>
    <referenceTo>Locations__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Access_Type__c.field-meta.xml
<CustomField>
    <fullName>Access_Type__c</fullName>
    <label>Access Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Access_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>Order_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Location</label>
    <referenceTo>Locations__c</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>Order_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>Order_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Locations__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Access_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Hourly</fullName>
    </customValue>
    <customValue>
        <fullName>Daily</fullName>
    </customValue>
    <customValue>
        <fullName>Hourly Multi-Pass</fullName>
    </customValue>
    <customValue>
        <fullName>Daily Multi-Pass</fullName>
    </customValue>
    <customValue>
        <fullName>Periodic</fullName>
    </customValue>
    <customValue>
        <fullName>Monthly</fullName>
    </customValue>
    <customValue>
        <fullName>One-Time</fullName>
    </customValue>
    <customValue>
        <fullName>Series</fullName>
    </customValue>
    <customValue>
        <fullName>Credits</fullName>
        <isActive>false</isActive>
        <label>Credits</label>
    </customValue>
    <masterLabel>Access Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ContractPaymentsBatch.cls
/**
 * @description       : implement a batch that generate number of monthlyPayments
 * @author            : LAURIE CS
 * @group             :
 * @last modified on  : 2024-10-13
 **/
public class ContractPaymentsBatch implements Database.Batchable<SObject>, Schedulable {
  public Database.QueryLocator start(Database.BatchableContext BC) {
    List<MPbyMonths__mdt> mpSettings = [
      SELECT NumberOfMonths__c
      FROM MPbyMonths__mdt
      LIMIT 1
    ];
    Integer numberOfMP = (mpSettings.isEmpty() ||
      mpSettings[0].NumberOfMonths__c == null)
      ? 0
      : Integer.valueOf(mpSettings[0].NumberOfMonths__c);
    Date monthsFromToday = Date.today().addMonths(numberOfMP);
    return Database.getQueryLocator(
      'SELECT Id, ServiceDate, Opportunity_Product__c, Contract__r.Id, Contract__r.Opportunity__c, Product2Id, Contract__r.Location__c, ' +
        'Contract__r.Contract_Termination_Date__c, ' +
        'Access_Type__c, Contract__r.Status, Product2.Name, ListPrice, ' +
        '(SELECT Id, Start_date__c, End_date__c FROM Monthly_Payments__r ORDER BY End_date__c DESC LIMIT 1) ' +
        'FROM OrderItem ' +
        'WHERE (Access_Type__c = \'Monthly\' AND Contract__r.Status = \'Activated\') limit 50000'
    );
  }

  // Execute method: process each chunk of OrderItems
  public void execute(Database.BatchableContext BC, List<OrderItem> scope) {
    ContractService.generateMonthlyPaymentsForYearFromCrntDate(scope);
  }

  // Finish method: optional post-processing
  public void finish(Database.BatchableContext BC) {
  }

  /**
   * @description Executes the scheduled job.
   * @param context The schedulable context instance.
   * @return void This method does not return any value.
   **/
  public void execute(SchedulableContext context) {
    Database.executeBatch(new ContractPaymentsBatch(), 50);
  }
}