force-app/main/default/objects/Contract/fields/Contract_Termination_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_Termination_Date__c</fullName>
    <inlineHelpText>Manual termination</inlineHelpText>
    <label>Contract Termination Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Location</label>
    <referenceTo>Locations__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Locations__c.field-meta.xml
<CustomField>
    <fullName>Locations__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Locations</label>
    <referenceTo>Location</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Locations__c/Locations__c.object-meta.xml
<CustomObject>
    <label>Locations</label>
    <nameField>
        <label>Locations Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Locations__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Locations__c/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <label>Area</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Area</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Locations__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Tel Aviv</fullName>
            </value>
            <value>
                <fullName>Bnei Brak</fullName>
            </value>
            <value>
                <fullName>Ra&apos;anana</fullName>
            </value>
            <value>
                <fullName>Modiin</fullName>
            </value>
            <value>
                <fullName>Ramat Gan</fullName>
            </value>
            <value>
                <fullName>Petah Tikva</fullName>
            </value>
            <value>
                <fullName>Rishon LeZion</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Locations__c/fields/Site_Name__c.field-meta.xml
<CustomField>
    <fullName>Site_Name__c</fullName>
    <label>Site Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MonthlyPayment__c/MonthlyPayment__c.object-meta.xml
<CustomObject>
    <label>Monthly Payment</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Monthly Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Monthly Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MonthlyPayment__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Location of the Office</description>
    <label>Location</label>
    <referenceTo>Locations__c</referenceTo>
    <relationshipLabel>Monthly Payments</relationshipLabel>
    <relationshipName>MonthlyPayments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MonthlyPayment__c/fields/Room__c.field-meta.xml
<CustomField>
    <fullName>Room__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Monthly Payments</relationshipLabel>
    <relationshipName>Monthly_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Locations__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Location</label>
    <referenceTo>Locations__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Access_Type__c.field-meta.xml
<CustomField>
    <fullName>Access_Type__c</fullName>
    <label>Access Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Access_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>Order_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Location</label>
    <referenceTo>Locations__c</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>Order_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Locations__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Access_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Hourly</fullName>
    </customValue>
    <customValue>
        <fullName>Daily</fullName>
    </customValue>
    <customValue>
        <fullName>Hourly Multi-Pass</fullName>
    </customValue>
    <customValue>
        <fullName>Daily Multi-Pass</fullName>
    </customValue>
    <customValue>
        <fullName>Periodic</fullName>
    </customValue>
    <customValue>
        <fullName>Monthly</fullName>
    </customValue>
    <customValue>
        <fullName>One-Time</fullName>
    </customValue>
    <customValue>
        <fullName>Series</fullName>
    </customValue>
    <customValue>
        <fullName>Credits</fullName>
        <isActive>false</isActive>
        <label>Credits</label>
    </customValue>
    <masterLabel>Access Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Area.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Tel Aviv - Modiin</fullName>
    </customValue>
    <customValue>
        <fullName>Ra&apos;anana</fullName>
    </customValue>
    <customValue>
        <fullName>Petah Tikva - Ramat Gan - Bnei Brak</fullName>
    </customValue>
    <customValue>
        <fullName>Tel Aviv</fullName>
    </customValue>
    <customValue>
        <fullName>Modiin</fullName>
    </customValue>
    <customValue>
        <fullName>Petah Tikva</fullName>
    </customValue>
    <customValue>
        <fullName>Bne Brak</fullName>
    </customValue>
    <customValue>
        <fullName>Ramat Gan</fullName>
    </customValue>
    <customValue>
        <fullName>Rishon LeZion</fullName>
    </customValue>
    <customValue>
        <fullName>Glilot Allied City</fullName>
    </customValue>
    <masterLabel>Area</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ContractServiceTest.cls
@isTest
public with sharing class ContractServiceTest {

    @testSetup
    static void setup() {
        Locations__c loc = new Locations__c(
            Name = 'BSR City',
            City__c = 'Petah Tikva',
            Site_Name__c = 'BSR City',
            Address__c = 'בניין Y - השחם 3 פינת תוצרת הארץ 1, פתח תקווה',
            Area__c = 'Petah Tikva - Ramat Gan - Bnei Brak'
        );
        insert loc;

        Account acc = new Account(Name = 'Test Account');
        insert acc;

        Id pricebookId = Test.getStandardPricebookId();

        Product2 prod = new Product2(Name = 'SLA: Bronze', IsActive = true);
        insert prod;

        PricebookEntry standardPBE = new PricebookEntry(
            Pricebook2Id = pricebookId,
            Product2Id = prod.Id,
            UnitPrice = 1000,
            IsActive = true
        );
        insert standardPBE;

        Opportunity opp = new Opportunity(
            Name = 'Test Opportunity',
            CloseDate = Date.today().addMonths(1),
            StageName = 'New',
            Location__c = loc.Id,
            Pricebook2Id = pricebookId
        );
        insert opp;

        Order orderRecord = new Order(
            AccountId = acc.Id,
            Pricebook2Id = pricebookId,
            OpportunityId = opp.Id,
            EffectiveDate = Date.today(),
            Status = 'Draft',
            location__c = loc.Id
        );
        insert orderRecord;

        orderItem orderItem = new orderItem(
            orderId = orderRecord.Id,
            PricebookEntryId = standardPBE.Id,
            Quantity = 1,
            ServiceDate = Date.today(),
            EndDate = Date.today().addYears(1).addMonths(1),
            Access_Type__c = 'Periodic',
            UnitPrice = 12
        );
        insert orderItem;

        orderItem orderItemWithoutEndDate = new orderItem(
            orderId = orderRecord.Id,
            PricebookEntryId = standardPBE.Id,
            Quantity = 1,
            ServiceDate = Date.today(),
            Access_Type__c = 'Monthly',
            UnitPrice = 12
        );
        insert orderItemWithoutEndDate;


        List<MonthlyPayment__c> testPayments = new List<MonthlyPayment__c>();
        for (Integer i = 0; i < 12; i++) {
            Date startDate = Date.today().toStartOfMonth().addMonths(i);
            testPayments.add(new MonthlyPayment__c(
                orderItem__c = orderItem.Id,
                Room__c = prod.Id,
                Location__c = loc.Id,
                Stat_Date_Trigger__c = startDate,
                End_Date_trigger__c = startDate.addDays(29)
            ));
        }
        List<MonthlyPayment__c> testPayments2 = new List<MonthlyPayment__c>();
        for (Integer i = 0; i < 12; i++) {
            Date startDate = Date.today().toStartOfMonth().addMonths(i);
            testPayments.add(new MonthlyPayment__c(
                orderItem__c = orderItemWithoutEndDate.Id,
                Room__c = prod.Id,
                Location__c = loc.Id,
                Stat_Date_Trigger__c = startDate
            ));
        }

        insert testPayments;
        insert testPayments2;
    }

    @isTest
    static void testGenerateMonthlyPaymentsRelatedToOrderItems() {
        Map<Id, OrderItem> orderItemsMap = new Map<Id, OrderItem>([SELECT Id, ServiceDate FROM OrderItem LIMIT 1]);

        Test.startTest();
        ContractService.generateMonthlyPaymentsRelatedToOrderItems(orderItemsMap);
        Test.stopTest();

        List<MonthlyPayment__c> payments = [SELECT Id FROM MonthlyPayment__c WHERE OrderItem__c IN :orderItemsMap.keySet()];
        System.assert(!payments.isEmpty(), 'Monthly payments should be generated.');
    }

    @isTest
    static void testGenerateMonthlyPaymentsForYearFromCrntDate() {
        List<OrderItem> orderItems = [SELECT Contract__r.Contract_Termination_Date__c, Id, ListPrice, EndDate, Access_Type__c, Contract__r.Location__c, Product2Id, Contract__c, ServiceDate FROM OrderItem LIMIT 1];

        Test.startTest();
        ContractService.generateMonthlyPaymentsForYearFromCrntDate(orderItems);
        Test.stopTest();

        List<MonthlyPayment__c> payments = [SELECT Id FROM MonthlyPayment__c WHERE OrderItem__c IN :orderItems];
        System.assert(!payments.isEmpty(), 'Monthly payments should be generated.');
    }

    @isTest
    static void testDeleteAllMonthlyPaymentRelatedToOrderItem() {
        Map<Id, OrderItem> orderItemsMap = new Map<Id, OrderItem>([SELECT Id FROM OrderItem LIMIT 1]);

        Test.startTest();
        ContractService.deleteAllMonthlyPaymentRelatedToOrderItem(orderItemsMap);
        Test.stopTest();

        List<MonthlyPayment__c> payments = [SELECT Id FROM MonthlyPayment__c WHERE OrderItem__c IN :orderItemsMap.keySet()];
        System.assert(payments.isEmpty(), 'All monthly payments related to OrderItems should be deleted.');
    }

    @isTest
    static void testDeleteAllMonthlyPaymentAndRecalculate() {
        Map<Id, OrderItem> orderItemsNew = new Map<Id, OrderItem>([SELECT Id, ListPrice, EndDate, Access_Type__c, Contract__r.Location__c, Product2Id, Contract__c, ServiceDate FROM OrderItem LIMIT 1]);
        Map<Id, OrderItem> orderItemsOld = new Map<Id, OrderItem>([SELECT Id,ListPrice, EndDate, Access_Type__c, Contract__r.Location__c, Product2Id, Contract__c, ServiceDate FROM OrderItem LIMIT 1]);

        Test.startTest();
        ContractService.deleteAllMonthlyPaymentAndRecalculate(orderItemsNew, orderItemsOld);
        Test.stopTest();

        List<MonthlyPayment__c> payments = [SELECT Id  FROM MonthlyPayment__c WHERE OrderItem__c IN :orderItemsNew.keySet()];
        System.assert(!payments.isEmpty(), 'Monthly payments should be recalculated after deletion.');
    }

    @isTest
    static void testDeleteAllMonthlyPaymentNotRelevant() {
        Map<Id, OrderItem> orderItemsNew = new Map<Id, OrderItem>([SELECT Id, ServiceDate, EndDate, Access_Type__c FROM OrderItem LIMIT 1]);
        Map<Id, OrderItem> orderItemsOld = new Map<Id, OrderItem>([SELECT Id, ServiceDate, EndDate, Access_Type__c FROM OrderItem LIMIT 1]);

        Test.startTest();
        ContractService.deleteAllMonthlyPaymentNotRelevant(orderItemsNew, orderItemsOld);
        Test.stopTest();

        List<MonthlyPayment__c> payments = [SELECT Id FROM MonthlyPayment__c WHERE OrderItem__c IN :orderItemsNew.keySet()];
        System.assert(!payments.isEmpty(), 'Only relevant monthly payments should remain.');
    }
    @isTest
    static void testDeleteAllMonthlyPaymentNotRelevantWithoutEnddate() {
        Map<Id, OrderItem> orderItemsNew = new Map<Id, OrderItem>([SELECT Id,ListPrice, EndDate, Access_Type__c, Contract__r.Location__c, Product2Id, Contract__c, ServiceDate, Period_In_Months__c FROM OrderItem  where EndDate != null LIMIT 1]);
        Map<Id, OrderItem> orderItemsOld = new Map<Id, OrderItem>([SELECT Id, ListPrice, EndDate, Access_Type__c, Contract__r.Location__c, Product2Id, Contract__c, ServiceDate, Period_In_Months__c FROM OrderItem where EndDate = null LIMIT 1]);

        Test.startTest();
        ContractService.deleteAllMonthlyPaymentNotRelevant(orderItemsNew, orderItemsOld);
        Test.stopTest();

        List<MonthlyPayment__c> payments = [SELECT Id FROM MonthlyPayment__c WHERE OrderItem__c IN :orderItemsNew.keySet()];
        System.assert(!payments.isEmpty(), 'Only relevant monthly payments should remain.');
    }

    @isTest
    static void testPublishEvent() {
        Test.startTest();
        ContractService.publishEvent();
        Test.stopTest();

        System.assert(true, 'Event publishing tested');
    }

    @isTest
    static void testBeforeDelete_Exception() {
        OrderItem testOrderItem = [SELECT Id FROM OrderItem LIMIT 1];
        Map<Id, SObject> orderItemNMap = new Map<Id, SObject>{testOrderItem.Id => testOrderItem};

        Test.startTest();
        try {
            OrderItemTriggerHandler handler = new OrderItemTriggerHandler();
            handler.beforeDelete(orderItemNMap);
            System.assert(false, 'Expected an exception due to invalid data');
        } catch (Exception e) {
            System.assert(true, 'Caught expected exception in beforeDelete');
        }
        Test.stopTest();
    }





}