force-app/main/default/objects/Contract/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Location</label>
    <referenceTo>Locations__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Locations__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Access_Type__c.field-meta.xml
<CustomField>
    <fullName>Access_Type__c</fullName>
    <label>Access Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Access_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>Order_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Location</label>
    <referenceTo>Locations__c</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>Order_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/Calculated_Price__c.field-meta.xml
<CustomField>
    <fullName>Calculated_Price__c</fullName>
    <formula>IF(  ISPICKVAL( Product2.Type__c , &apos;Standard Products&apos;),  UnitPrice /Capacity_Desks__c ,UnitPrice )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Calculated Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/Capacity_Desks__c.field-meta.xml
<CustomField>
    <fullName>Capacity_Desks__c</fullName>
    <formula>Product2.Capacity_Desks__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Capacity (Desks)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Calculated_Price__c.field-meta.xml
<CustomField>
    <fullName>Calculated_Price__c</fullName>
    <formula>IF( ISPICKVAL( Type__c , &apos;Standard Products&apos;),  Destination_Price__c /  Capacity_Desks__c  ,Destination_Price__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Calculated Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Capacity_Desks__c.field-meta.xml
<CustomField>
    <fullName>Capacity_Desks__c</fullName>
    <label>Capacity (Desks)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Floor__c.field-meta.xml
<CustomField>
    <fullName>Floor__c</fullName>
    <label>Floor</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Locations__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Sub_Type__c</fullName>
    <label>Sub-Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hot Desk</fullName>
            </value>
            <value>
                <fullName>Open Space</fullName>
            </value>
            <value>
                <fullName>Office</fullName>
            </value>
            <value>
                <fullName>Suite</fullName>
            </value>
            <value>
                <fullName>Rent</fullName>
            </value>
            <value>
                <fullName>Daily HD</fullName>
            </value>
            <value>
                <fullName>Daily Office</fullName>
            </value>
            <value>
                <fullName>Meeting Rooms</fullName>
            </value>
            <value>
                <fullName>Event Space-Balcony, roof, Lounge</fullName>
            </value>
            <value>
                <fullName>Mini Cinema</fullName>
            </value>
            <value>
                <fullName>Classroom</fullName>
            </value>
            <value>
                <fullName>Parking spot</fullName>
            </value>
            <value>
                <fullName>Capsules</fullName>
            </value>
            <value>
                <fullName>Food / Refreshements</fullName>
            </value>
            <value>
                <fullName>IP/VLAN</fullName>
            </value>
            <value>
                <fullName>Credits(Meeting rooms windows)</fullName>
            </value>
            <value>
                <fullName>Print Units</fullName>
            </value>
            <value>
                <fullName>Storage Space</fullName>
            </value>
            <value>
                <fullName>Set Up Fee</fullName>
            </value>
            <value>
                <fullName>Restoration Fee</fullName>
            </value>
            <value>
                <fullName>Arnona</fullName>
            </value>
            <value>
                <fullName>Cleaning</fullName>
            </value>
            <value>
                <fullName>Electricity</fullName>
            </value>
            <value>
                <fullName>Management Fee</fullName>
            </value>
            <value>
                <fullName>Other- (all other fee)</fullName>
            </value>
            <value>
                <fullName>Podcast Room</fullName>
            </value>
            <value>
                <fullName>Maintenance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard Products</fullName>
            </value>
            <value>
                <fullName>On demand Products</fullName>
            </value>
            <value>
                <fullName>Extra for all products</fullName>
            </value>
            <value>
                <fullName>Extra for meter Products</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Window__c.field-meta.xml
<CustomField>
    <fullName>Window__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Window</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/globalValueSets/Access_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Hourly</fullName>
    </customValue>
    <customValue>
        <fullName>Daily</fullName>
    </customValue>
    <customValue>
        <fullName>Hourly Multi-Pass</fullName>
    </customValue>
    <customValue>
        <fullName>Daily Multi-Pass</fullName>
    </customValue>
    <customValue>
        <fullName>Periodic</fullName>
    </customValue>
    <customValue>
        <fullName>Monthly</fullName>
    </customValue>
    <customValue>
        <fullName>One-Time</fullName>
    </customValue>
    <customValue>
        <fullName>Series</fullName>
    </customValue>
    <customValue>
        <fullName>Credits</fullName>
        <isActive>false</isActive>
        <label>Credits</label>
    </customValue>
    <masterLabel>Access Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Changes from opportunity</fullName>
    </customValue>
    <customValue>
        <fullName>Existing Business</fullName>
    </customValue>
    <customValue>
        <fullName>New Business</fullName>
    </customValue>
    <customValue>
        <fullName>Renewal</fullName>
    </customValue>
    <customValue>
        <fullName>Returning Customer</fullName>
    </customValue>
    <masterLabel>Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AddOppProductController.cls
public without sharing class AddOppProductController {

    @AuraEnabled(cacheable=true)
    public static List<ProductData> getProductsByOppLocation(string oppId){
        Opportunity opp = [SELECT Id, RecordTypeId, RecordType.Name, Location__c FROM Opportunity WHERE Id = :oppId];

        String location = opp.Location__c;

        String baseQuery = 'SELECT Id, Name, Product2Id, Capacity_Desks__c, UnitPrice, Floor__c, Window__c, Calculated_Price__c, Product2.Type__c, Product2.Sub_Type__c, Product2.State__c ' +
                           'FROM PricebookEntry ' +
                           'WHERE Product2.Location__c = :location';

        if (opp.RecordType.Name == 'Series Opportunity' || opp.RecordType.Name == 'On demand Opportunity') {
            baseQuery += ' AND (Product2.Type__c = \'On demand Products\' OR Product2.Type__c = \'Extra for all products\')';
        } 
            
        List<PricebookEntry> pricebookEntries = Database.query(baseQuery);
        
        Set<Id> existingContractsByProduct = getExistingContracts(pricebookEntries);

        List<ProductData> productsData = new List<ProductData>();

        for(PricebookEntry pbe : pricebookEntries){
            ProductData prdData = new ProductData(pbe);
            
            if(pbe.Product2.Type__c == 'Standard Products' && pbe.Product2.Sub_Type__c != 'Hot Desk'){
                if(existingContractsByProduct.contains(pbe.Product2Id)){
                    prdData.Availability = '⚠️';
                }else{
                    prdData.Availability = '🟢';
                }
            }
            productsData.add(prdData);
        }

        return productsData;
    }

    private static Set<Id> getExistingContracts(List<PricebookEntry> pbes){
        Set<Id> existingContractsByProduct = new Set<Id>();
        List<string> productsIds = new List<string>();

        //get existing contracts for products:
        for(PricebookEntry pbe : pbes){
            if(pbe.Product2.Type__c == 'Standard Products' && pbe.Product2.Sub_Type__c != 'Hot Desk'){
                productsIds.add(pbe.Product2Id);
            }
        }

        if(productsIds.size() > 0){
            List<OrderItem> orderItems = [  SELECT Id, Product2Id, Product2.Name, Access_Type__c, ServiceDate, EndDate, Contract__r.Account.Name, Contract__c, Contract__r.ContractNumber,Contract__r.Status 
                                            FROM OrderItem 
                                            WHERE Contract__r.Status = 'Activated' AND Product2Id in :productsIds];

            for(OrderItem item : orderItems){
                existingContractsByProduct.add(item.Product2Id);
            }
        }

        return existingContractsByProduct;
    }

    @AuraEnabled
    public static String addProductsToOpp(List<String> productEntryIds, string opportunityId){
        //call flow - Prepare input variables
        Map<String, Object> inputVariables = new Map<String, Object>();
        inputVariables.put('InputVarProductEntryIds', productEntryIds);
        inputVariables.put('InputVarOportuntiyId', opportunityId);

        // The flow interview class should exist for your flow name
        Flow.Interview.Opportunity_Package_Builder_Manage_Opportunity_Products_2_0 flowInterview = new Flow.Interview.Opportunity_Package_Builder_Manage_Opportunity_Products_2_0(inputVariables);

        // Start the flow
        flowInterview.start();

        if(flowInterview.AddErrorMessage != null){
            return flowInterview.AddErrorMessage;
        }
        return '';
    }

    public class ProductData {
        @AuraEnabled
        public string Id {get; set;}
        @AuraEnabled
        public string Name {get; set;}
        @AuraEnabled
        public Decimal CapacityDesks {get; set;}
        @AuraEnabled
        public Decimal UnitPrice {get; set;}
        @AuraEnabled
        public Decimal Floor {get; set;}
        @AuraEnabled
        public Boolean Window {get; set;}
        @AuraEnabled
        public Decimal CalculatedPrice {get; set;}
        @AuraEnabled
        public string ProductType {get; set;}
        @AuraEnabled
        public string ProductSubType {get; set;}
        @AuraEnabled
        public string ProductState {get; set;}
        @AuraEnabled
        public string Availability {get; set;}
        
        public ProductData(PricebookEntry prod){
            this.Id = prod.Id;
            this.Name = prod.Name;
            this.CapacityDesks = prod.Capacity_Desks__c;
            this.UnitPrice = prod.UnitPrice;
            this.Floor = prod.Floor__c;
            this.Window = prod.Window__c;
            this.CalculatedPrice = prod.Calculated_Price__c;
            this.ProductType = prod.Product2.Type__c;
            this.ProductSubType = prod.Product2.Sub_Type__c;
            this.ProductState = prod.Product2.State__c;
            this.Availability = '';
        }
    }
}