force-app/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <label>Log</label>
    <nameField>
        <label>Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Log__c/fields/Error_Info__c.field-meta.xml
<CustomField>
    <fullName>Error_Info__c</fullName>
    <label>Error Info</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Error_Message__c</fullName>
    <label>Error Message</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Has_Error__c.field-meta.xml
<CustomField>
    <fullName>Has_Error__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has Error</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Logs</relationshipLabel>
    <relationshipName>Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Logs</relationshipLabel>
    <relationshipName>Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Partial Success</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Log.cls
public without sharing class Log {

    private static Log__c log = new Log__c(Body__c = '');
    public static Id insertedLoadId = null;

    public static void add(String message) {
        add(LoggingLevel.DEBUG, message);
    }

    public static void add(LoggingLevel logLevel, String message) {
        log.Body__c += logLevel + ' | ' + message + '\r\n';
        System.debug(logLevel, message);
        if(logLevel == LoggingLevel.ERROR){
            log.Has_Error__c = true;
            log.Error_Message__c = message;
            log.Status__c = 'Error';
        }
    }

    public static void add(Database.Error err) {
        String errorMessage = err.getStatusCode() + ': ' + err.getMessage() + '\r\n';
        errorMessage += 'Fields : ' + err.getFields();
        log.Has_Error__c = true;
        add(LoggingLevel.ERROR, errorMessage);
    }

    public static void add(Exception ex) {
        String errorMessage = ex.getMessage() + '\r\n';
        errorMessage += ex.getStackTraceString();
        log.Has_Error__c = true;
        add(LoggingLevel.ERROR, errorMessage);
    }

    public static void setRelatedOpportunity(String opportunityId) {
        log.Opportunity__c = opportunityId;
    }
    
    public static void setRelatedLead(String leadId) {
        log.Lead__c = leadId;
    }

    public static void setLogName(String logName) {
        log.Name = logName;
    }

    public static void setLogDescription(String description) {
        log.Description__c = description;
    }
    
    public static void setErrorInfo(String errorInfo) {
        log.Error_Info__c = errorInfo;
    }
    
    public static void setStatus(String status) {
        log.Status__c = status;
    }
    
    public static void setObject(String obj) {
        log.Object__c = obj;
    }
    
    public static void insertLog() {
        insert log;
        insertedLoadId = log.Id;
        log = new Log__c(Body__c = '');
    }
}