force-app/main/default/objects/Lead/fields/Desired_Location__c.field-meta.xml
<CustomField>
    <fullName>Desired_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Desired Location</label>
    <referenceTo>Locations__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Lost_Reason__c.field-meta.xml
<CustomField>
    <fullName>Lost_Reason__c</fullName>
    <label>Lost Reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Incorrect Details</fullName>
            </value>
            <value>
                <fullName>Looking for Hotel In Fattal</fullName>
            </value>
            <value>
                <fullName>No Response</fullName>
            </value>
            <value>
                <fullName>System Check</fullName>
            </value>
            <value>
                <fullName>Not relevant to the Sales Department</fullName>
            </value>
            <value>
                <fullName>Customer stopped answering - after 6 attempts</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Cancelled Lead</fullName>
            </value>
            <value>
                <fullName>Moked - City without ROOMS sites</fullName>
            </value>
            <value>
                <fullName>Moked - Low budget</fullName>
            </value>
            <value>
                <fullName>Moked - Looking for an independent office</fullName>
            </value>
            <value>
                <fullName>Moked - Customer changed their mind</fullName>
            </value>
            <value>
                <fullName>Moked - Customer signed with competitor</fullName>
            </value>
            <value>
                <fullName>Moked - Site didnt open yet</fullName>
            </value>
            <value>
                <fullName>Complex s Service request</fullName>
            </value>
            <value>
                <fullName>Customer stopped responding</fullName>
                <isActive>false</isActive>
                <label>Customer stopped responding</label>
            </value>
            <value>
                <fullName>Duplicate lead</fullName>
                <isActive>false</isActive>
                <label>Duplicate lead</label>
            </value>
            <value>
                <fullName>Incorrect information</fullName>
                <isActive>false</isActive>
                <label>Incorrect information</label>
            </value>
            <value>
                <fullName>Maybe in the future</fullName>
                <isActive>false</isActive>
                <label>Maybe in the future</label>
            </value>
            <value>
                <fullName>Not relevant</fullName>
                <isActive>false</isActive>
                <label>Not relevant</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BrazeSyncCalloutBatch.cls
global class BrazeSyncCalloutBatch implements Database.Batchable<sObject>, Database.AllowsCallouts {

    private List<Id> recordIds;
    private String recordType;

    // Constructor
    global BrazeSyncCalloutBatch(List<Id> recIds, String type){
        this.recordIds = recIds;
        this.recordType = type;
    }

    // Start method: query records
    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator([
            SELECT Id, FirstName, LastName, Email, MobilePhone, Status, Lost_Reason__c, Desired_Location__c, ConvertedOpportunityId, OwnerId, CreatedDate
            FROM Lead WHERE Id IN :recordIds
        ]);
    }

    // Execute method: process each batch
    global void execute(Database.BatchableContext BC, List<sObject> scope){
        Http http = new Http();

        for(sObject rec : scope){
            try {
                Lead leadRec = (Lead) rec;
                Log.setLogName('Rooms Braze Integration');
                Log.setLogDescription('Braze Sync Callout Service | lead id: ' + leadRec.Id);
                
                Log.add('Class: BrazeSyncCalloutBatch');
                Log.setRelatedLead(leadRec.Id);
					
                BrazeRequestWrapper payload = new BrazeRequestWrapper(leadRec, recordType);
                String recordIdToLog;

                if(this.recordType == 'Opportunity' && !payload.opportunities.isEmpty()){
                    recordIdToLog = payload.opportunities[0].Id;
                    Log.setRelatedOpportunity(recordIdToLog);
                } else {
                    recordIdToLog = leadRec.Id;
                }
                
                HttpRequest req = new HttpRequest();
                req.setEndpoint('callout:Braze_Rest/users/track'); // Named Credential
                req.setMethod('POST');
                req.setHeader('Content-Type','application/json');
                String requestBody = JSON.serialize(payload).replace('event_time', 'time');
                Log.add('req Body: ' + requestBody);
                req.setBody(requestBody);
                HttpResponse res = http.send(req);
                Log.add('res body: '+ res.getBody());
                
                if (res.getStatusCode() >= 200 && res.getStatusCode() < 300) {
                    Log.add(LoggingLevel.INFO, 'Success for ' + this.recordType +': ' + recordIdToLog + ' | Status: ' + res.getStatusCode());
                } else {
                    Log.add(LoggingLevel.ERROR,
                        'Failed for ' + this.recordType +': ' + recordIdToLog +
                        ' | Status Code: ' + res.getStatusCode() +
                        ' | Status: ' + res.getStatus() +
                        ' | Response Body: ' + res.getBody()
                    );
                }
            }catch(Exception ex) {
            	Log.add(ex);
            }finally {
                Log.insertLog();
            }
        }
    }

    // Finish method
    global void finish(Database.BatchableContext BC){
        // Optional: send email or logging
    }
}