force-app/main/default/objects/Contact/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Client</fullName>
                <default>true</default>
                <label>Client</label>
            </value>
            <value>
                <fullName>Broker</fullName>
            </value>
            <value>
                <fullName>Employee</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/End_date__c.field-meta.xml
<CustomField>
    <fullName>End_date__c</fullName>
    <label>End date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Location</label>
    <referenceTo>Locations__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Locations__c.field-meta.xml
<CustomField>
    <fullName>Locations__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Locations</label>
    <referenceTo>Location</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Main_Contact__c.field-meta.xml
<CustomField>
    <fullName>Main_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Main Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Members_Registred__c.field-meta.xml
<CustomField>
    <fullName>Members_Registred__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Members Registred</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Locations__c/Locations__c.object-meta.xml
<CustomObject>
    <label>Locations</label>
    <nameField>
        <label>Locations Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Locations__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Locations__c/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <label>Area</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Area</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Locations__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Tel Aviv</fullName>
            </value>
            <value>
                <fullName>Bnei Brak</fullName>
            </value>
            <value>
                <fullName>Ra&apos;anana</fullName>
            </value>
            <value>
                <fullName>Modiin</fullName>
            </value>
            <value>
                <fullName>Ramat Gan</fullName>
            </value>
            <value>
                <fullName>Petah Tikva</fullName>
            </value>
            <value>
                <fullName>Rishon LeZion</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Locations__c/fields/Desk_Count__c.field-meta.xml
<CustomField>
    <fullName>Desk_Count__c</fullName>
    <description>Aggregated count of desks for standard products - Used in reports and dash</description>
    <label>Desk Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Locations__c/fields/Site_Name__c.field-meta.xml
<CustomField>
    <fullName>Site_Name__c</fullName>
    <label>Site Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Locations__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Main_Contact__c.field-meta.xml
<CustomField>
    <fullName>Main_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Main Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Main Contact)</relationshipLabel>
    <relationshipName>Opportunities2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product_Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Sub_Type__c</fullName>
    <label>Product Sub-Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Product_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Hot Desk</fullName>
            </value>
            <value>
                <fullName>Open Space</fullName>
            </value>
            <value>
                <fullName>Office</fullName>
            </value>
            <value>
                <fullName>Suite</fullName>
            </value>
            <value>
                <fullName>Rent</fullName>
            </value>
            <value>
                <fullName>Daily HD</fullName>
            </value>
            <value>
                <fullName>Daily Office</fullName>
            </value>
            <value>
                <fullName>Meeting Rooms</fullName>
            </value>
            <value>
                <fullName>Event Space-Balcony, roof, Lounge</fullName>
            </value>
            <value>
                <fullName>Mini Cinema</fullName>
            </value>
            <value>
                <fullName>Podcast Room</fullName>
            </value>
            <value>
                <fullName>Classroom</fullName>
            </value>
            <value>
                <fullName>Parking spot</fullName>
            </value>
            <value>
                <fullName>Capsules</fullName>
            </value>
            <value>
                <fullName>Food / Refreshements</fullName>
            </value>
            <value>
                <fullName>IP/VLAN</fullName>
            </value>
            <value>
                <fullName>Credits(Meeting rooms windows)</fullName>
            </value>
            <value>
                <fullName>Print Units</fullName>
            </value>
            <value>
                <fullName>Storage Space</fullName>
            </value>
            <value>
                <fullName>Set Up Fee</fullName>
            </value>
            <value>
                <fullName>Restoration Fee</fullName>
            </value>
            <value>
                <fullName>Arnona</fullName>
            </value>
            <value>
                <fullName>Cleaning</fullName>
            </value>
            <value>
                <fullName>Electricity</fullName>
            </value>
            <value>
                <fullName>Management Fee</fullName>
            </value>
            <value>
                <fullName>Other- (all other fee)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Desk_Count__c.field-meta.xml
<CustomField>
    <fullName>Desk_Count__c</fullName>
    <label>Desk Capacity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Products_Type__c.field-meta.xml
<CustomField>
    <fullName>Products_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard Products</fullName>
            </value>
            <value>
                <fullName>On demand Products</fullName>
            </value>
            <value>
                <fullName>Extra for all products</fullName>
            </value>
            <value>
                <fullName>Extra for meter Products</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <formula>text( Product__r.Type__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Desk_Count__c.field-meta.xml
<CustomField>
    <fullName>Desk_Count__c</fullName>
    <label>Desk Count</label>
    <summarizedField>OrderItem.Quantity</summarizedField>
    <summaryFilterItems>
        <field>OrderItem.Product_Type_Name__c</field>
        <operation>contains</operation>
        <value>Standard</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>OrderItem.Temporary__c</field>
        <operation>equals</operation>
        <value>False</value>
    </summaryFilterItems>
    <summaryForeignKey>OrderItem.OrderId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Order/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Location</label>
    <referenceTo>Locations__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Access_Type__c.field-meta.xml
<CustomField>
    <fullName>Access_Type__c</fullName>
    <label>Access Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Access_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>Order_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Location</label>
    <referenceTo>Locations__c</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>Order_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Locations__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard Products</fullName>
            </value>
            <value>
                <fullName>On demand Products</fullName>
            </value>
            <value>
                <fullName>Extra for all products</fullName>
            </value>
            <value>
                <fullName>Extra for meter Products</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Access_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Hourly</fullName>
    </customValue>
    <customValue>
        <fullName>Daily</fullName>
    </customValue>
    <customValue>
        <fullName>Hourly Multi-Pass</fullName>
    </customValue>
    <customValue>
        <fullName>Daily Multi-Pass</fullName>
    </customValue>
    <customValue>
        <fullName>Periodic</fullName>
    </customValue>
    <customValue>
        <fullName>Monthly</fullName>
    </customValue>
    <customValue>
        <fullName>One-Time</fullName>
    </customValue>
    <customValue>
        <fullName>Series</fullName>
    </customValue>
    <customValue>
        <fullName>Credits</fullName>
        <isActive>false</isActive>
        <label>Credits</label>
    </customValue>
    <masterLabel>Access Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Area.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Tel Aviv - Modiin</fullName>
    </customValue>
    <customValue>
        <fullName>Ra&apos;anana</fullName>
    </customValue>
    <customValue>
        <fullName>Petah Tikva - Ramat Gan - Bnei Brak</fullName>
    </customValue>
    <customValue>
        <fullName>Tel Aviv</fullName>
    </customValue>
    <customValue>
        <fullName>Modiin</fullName>
    </customValue>
    <customValue>
        <fullName>Petah Tikva</fullName>
    </customValue>
    <customValue>
        <fullName>Bne Brak</fullName>
    </customValue>
    <customValue>
        <fullName>Ramat Gan</fullName>
    </customValue>
    <customValue>
        <fullName>Rishon LeZion</fullName>
    </customValue>
    <customValue>
        <fullName>Glilot Allied City</fullName>
    </customValue>
    <masterLabel>Area</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Changes from opportunity</fullName>
    </customValue>
    <customValue>
        <fullName>Existing Business</fullName>
    </customValue>
    <customValue>
        <fullName>New Business</fullName>
    </customValue>
    <customValue>
        <fullName>Renewal</fullName>
    </customValue>
    <customValue>
        <fullName>Returning Customer</fullName>
    </customValue>
    <masterLabel>Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/OpportunityProductController_Test.cls
@isTest
public with sharing class OpportunityProductController_Test {
    @testSetup
    static void setup() {
        Date testDate = System.now().date().addDays(-10);

        Locations__c loc = new Locations__c(
            Name = 'BSR City',
            City__c = 'Petah Tikva',
            Site_Name__c = 'BSR City',
            Address__c = 'בניין Y - השחם 3 פינת תוצרת הארץ 1, פתח תקווה',
            Area__c = 'Petah Tikva - Ramat Gan - Bnei Brak'
        );
        insert loc;

        Account acc = new Account(Name = 'Test Account');
        insert acc;

        Contact con = new Contact(lastName = 'test',Email='alex@test.com', AccountId = acc.Id);
        insert con;

        Contract contract = new Contract(AccountId = acc.Id, Type__c = 'New Business', status = 'Draft', StartDate = testDate, Members_Registred__c = false, Main_contact__c=con.id);
        insert contract;

        contract.Status = 'Activated';
        update contract;

        Id pricebookId = Test.getStandardPricebookId();

        Product2 prod = new Product2(Name = 'SLA: Bronze', IsActive = true);
        insert prod;

        PricebookEntry standardPBE = new PricebookEntry(
            Pricebook2Id = pricebookId,
            Product2Id = prod.Id,
            UnitPrice = 1000,
            IsActive = true
        );
        insert standardPBE;

        Opportunity opp = new Opportunity(
            Name = 'Test Opportunity',
            CloseDate = Date.today().addMonths(1),
            StageName = 'New',
            Location__c = loc.Id,
            Pricebook2Id = pricebookId,
            RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Standard Opportunity').getRecordTypeId()
        );
        insert opp;
        
        OpportunityLineItem oli = new OpportunityLineItem(
            OpportunityId = opp.Id,
            UnitPrice = 1000,
            PricebookEntryId = standardPBE.Id,
            Quantity = 1,
            Products_Type__c = 'Standard Products',
            Entry_Date__c = Date.today().addMonths(1),
            End_date__c = Date.today().addMonths(2)
        );

        Order orderRecord = new Order(
            AccountId = acc.Id,
            Pricebook2Id = pricebookId,
            OpportunityId = opp.Id,
            EffectiveDate = Date.today(),
            Status = 'Draft',
            location__c = loc.Id
        );
        insert orderRecord;

        orderItem orderItem = new orderItem(
            orderId = orderRecord.Id,
            Contract__c = contract.Id,
            PricebookEntryId = standardPBE.Id,
            Quantity = 1,
            ServiceDate = Date.today().addYears(1),
            EndDate = Date.today().addYears(1).addMonths(3),
            Access_Type__c = 'Periodic',
            UnitPrice = 12
        );
        insert orderItem;

        orderItem orderItemWithoutEndDate = new orderItem(
            orderId = orderRecord.Id,
            Contract__c = contract.Id,
            PricebookEntryId = standardPBE.Id,
            Quantity = 1,
            ServiceDate = Date.today(),
            Access_Type__c = 'Monthly',
            UnitPrice = 12,
            EndDate = Date.today().addMonths(3)
        );
        insert orderItemWithoutEndDate;

        insert oli;

    }

    @isTest
    static void getOppProducts_test() {
        Opportunity opp = [SELECT Id, Name FROM Opportunity LIMIT 1];
        Id oppId = opp.Id;
        List<OpportunityProductController.OpportunityProductData> olis = OpportunityProductController.getOppProducts(oppId);

        Assert.areEqual(1, olis.size());
    }

    @isTest
    static void saveLineItemsSuccess_test() {
        string recordTypeName = 'On demand Opportunity';
        Opportunity opp = [SELECT Id, Name FROM Opportunity LIMIT 1];
        Id oppId = opp.Id;

        List<string> oliIds = new List<string>();

        List<OpportunityLineItem> lineItems = [
                                                SELECT Id, Opportunity.RecordTypeId, Opportunity.RecordType.Name, Product2Id, Product2.Name, UnitPrice,
                                                    Desk_Count__c, Access_Type__c, Entry_Date__c, End_date__c,Products_Type__c, Product_Sub_Type__c,
                                                    Quantity, TotalPrice, Temporary__c, Description, ListPrice
                                                FROM OpportunityLineItem
                                                WHERE OpportunityId = :oppId
                                            ];

        for (OpportunityLineItem oli : lineItems) {
            oliIds.add(oli.Id);
        }

        OpportunityProductController.UpdateRecordResult result = OpportunityProductController.saveLineItems(recordTypeName, oliIds, lineItems);

        Assert.areEqual(false, result.hasErrors);
    }

    @isTest
    static void saveLineItemsError1_test() {
        string recordTypeName = 'On demand Opportunity';
        Opportunity opp = [SELECT Id, Name FROM Opportunity LIMIT 1];
        Id oppId = opp.Id;

        List<OpportunityLineItem> lineItems = [
                                                SELECT Id, Opportunity.RecordTypeId, Opportunity.RecordType.Name, Product2Id, Product2.Name, UnitPrice,
                                                    Desk_Count__c, Access_Type__c, Entry_Date__c, End_date__c,Products_Type__c, Product_Sub_Type__c,
                                                    Quantity, TotalPrice, Temporary__c, Description, ListPrice
                                                FROM OpportunityLineItem
                                                WHERE OpportunityId = :oppId
                                            ];

        List<string> oliIds = new List<string>();
        for (OpportunityLineItem oli : lineItems) {
            oliIds.add(oli.Id);

            oli.Access_Type__c = 'Daily';
            oli.Quantity = 4;
        }

        OpportunityProductController.UpdateRecordResult result = OpportunityProductController.saveLineItems(recordTypeName, oliIds, lineItems);
        Assert.areEqual(true, result.hasErrors);
    }

    @isTest
    static void saveLineItemsError2_test() {
        string recordTypeName = 'Standard Opportunity';
        Opportunity opp = [SELECT Id, Name FROM Opportunity LIMIT 1];
        Id oppId = opp.Id;

        List<OpportunityLineItem> lineItems = [
                                                SELECT Id, Opportunity.RecordTypeId, Opportunity.RecordType.Name, Product2Id, Product2.Name, UnitPrice,
                                                    Desk_Count__c, Access_Type__c, Entry_Date__c, End_date__c,Products_Type__c, Product_Sub_Type__c,
                                                    Quantity, TotalPrice, Temporary__c, Description, ListPrice
                                                FROM OpportunityLineItem
                                                WHERE OpportunityId = :oppId
                                            ];

        List<string> oliIds = new List<string>();
        for (OpportunityLineItem oli : lineItems) {
            oliIds.add(oli.Id);

            oli.Access_Type__c = 'Monthly';
            oli.End_date__c = Date.today();
            oli.Quantity = 4;
            oli.Temporary__c = true;
        }

        OpportunityProductController.UpdateRecordResult result = OpportunityProductController.saveLineItems(recordTypeName, oliIds, lineItems);
        Assert.areEqual(true, result.hasErrors);
    }

    @isTest
    static void deleteLineItems_test() {

        string res = OpportunityProductController.deleteLineItems(null);
        Assert.areEqual('No items to delete', res);

        Opportunity opp = [SELECT Id, Name FROM Opportunity LIMIT 1];
        Id oppId = opp.Id;
        List<OpportunityLineItem> lineItems = [
                                                SELECT Id, Opportunity.RecordTypeId, Opportunity.RecordType.Name, Product2Id, Product2.Name, UnitPrice,
                                                    Desk_Count__c, Access_Type__c, Entry_Date__c, End_date__c,Products_Type__c, Product_Sub_Type__c,
                                                    Quantity, TotalPrice, Temporary__c, Description, ListPrice
                                                FROM OpportunityLineItem
                                                WHERE OpportunityId = :oppId
                                            ];

        List<string> itemIds = new List<string>();
        for (OpportunityLineItem oli : lineItems) {
            itemIds.add(oli.Id);
        }
        res = OpportunityProductController.deleteLineItems(itemIds);
        Assert.areEqual('Success', res);
    }

    @isTest
    static void getContracts_test(){
        Opportunity opp = [SELECT Id, Name FROM Opportunity LIMIT 1];
        Id oppId = opp.Id;
        
        List<OpportunityProductController.OpportunityProductData> olis = OpportunityProductController.getContracts(oppId);
    }
}